### ISSUE TITLE
Error loading RS jni library

### ISSUE THREAD

**Issue by audiultx** [Manabu-GT/GlassView#4]
Hi i don't know if anyone else have had this problem but i am getting:

**Rendering Problems**
`android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: no rsjni in java.library.path Support lib API: 2301   at android.support.v8.renderscript.RenderScript.internalCreate(RenderScript.java:1391)   at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1576)   at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1526)   at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1502)   at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1489)   at com.ms.square.android.glassview.GlassView.onAttachedToWindow(GlassView.java:174)   at android.view.View.dispatchAttachedToWindow(View.java:15392)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2953)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)   at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)`

in my xml file. It breaks the android studio preview.

**Comment by Manabu-GT** [comment]
This library is deprecated. In case if you are still looking for solution to this problem, please use https://github.com/Manabu-GT/EtsyBlur#blurringview instead. The BlurringView has a capability of falling back to java's fastblur implementation if it it encounters the error you posted.

Thank you.
